# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/jwt.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/jwt.proto", syntax: :proto3) do
    add_message "auth.ValidResponse" do
      optional :valid, :bool, 1
    end
  end
end

module Auth
  ValidResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("auth.ValidResponse").msgclass
end
