# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/media.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/media.proto", syntax: :proto3) do
    add_message "asset.GenerateUrlReq" do
      optional :resource_id, :uint32, 1
      optional :resource_type, :string, 2
      optional :media_type, :string, 3
      optional :file_name, :string, 4
      optional :storage_type, :string, 5
    end
    add_message "asset.GetMediaReq" do
      optional :resource_id, :uint32, 1
      optional :resource_type, :string, 2
      optional :media_type, :string, 3
    end
    add_message "asset.DeleteMediaReq" do
      optional :key, :string, 1
    end
    add_message "asset.AcknowledgeReq" do
      optional :key, :string, 1
    end
    add_message "asset.GenerateUrlResp" do
      optional :presigned_url, :string, 1
      optional :key, :string, 2
    end
    add_message "asset.AcknowledgeResp" do
      optional :success, :bool, 1
    end
    add_message "asset.MediaTracking" do
      optional :id, :uint32, 1
      optional :resource_id, :uint32, 2
      optional :resource_type, :string, 3
      optional :media_type, :string, 4
      optional :s3_key, :string, 5
      optional :access_url, :string, 6
      optional :status, :string, 7
      optional :storage_type, :string, 8
    end
    add_message "asset.GetMediaResp" do
      repeated :data, :message, 1, "asset.MediaTracking"
    end
  end
end

module Asset
  GenerateUrlReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.GenerateUrlReq").msgclass
  GetMediaReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.GetMediaReq").msgclass
  DeleteMediaReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.DeleteMediaReq").msgclass
  AcknowledgeReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.AcknowledgeReq").msgclass
  GenerateUrlResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.GenerateUrlResp").msgclass
  AcknowledgeResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.AcknowledgeResp").msgclass
  MediaTracking = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.MediaTracking").msgclass
  GetMediaResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("asset.GetMediaResp").msgclass
end
