# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/media.proto for package 'asset'

require 'grpc'

module Asset
  module MediaService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'asset.MediaService'

      rpc :GeneratePresignedUrl, ::Asset::GenerateUrlReq, ::Asset::GenerateUrlResp
      rpc :GetMedia, ::Asset::GetMediaReq, ::Asset::GetMediaResp
      rpc :DeleteMedia, ::Asset::AcknowledgeReq, ::Asset::AcknowledgeResp
      rpc :AcknowledgeUploaded, ::Asset::AcknowledgeReq, ::Asset::AcknowledgeResp
    end

    Stub = Service.rpc_stub_class
  end
end
